src/stack_license.py

https://github.com/openshiftio/openshift.io/issues/1013

Fixed issue #1013

---

src/stack_license.py
tests/test_stack_license.py

Fix issue https://github.com/openshiftio/openshift.io/issues/1172

Fix recommender worker failure issue with status key.

---

README.md
run-api-local.sh
run-test-local.sh
tests/test_license_analysis.py

Add steps to run test locally.

Modifications to run tests locally

---

openshift/template.yaml

See http://post-office.corp.redhat.com/archives/devtools-bayesian/2017-November/msg00065.html

[openshift] Lower cpu request/limit

---

requirements.txt
src/directed_graph.py
src/license_analysis.py
src/rest_api.py
src/stack_license.py
tests/test_license_analysis.py

* Fix import issues
* Fix dict{} key-values issues
* Remove un0use dependencies

Make repo python3 compatible

---

README.md

Updated README file with license tree diagram

---

src/stack_license.py

Changed output reason for the case when licenses for a component is absent.

Modified output message

---

tests/test_vertex.py

100% test coverage for the Vertex class

Tests for Vertex class

---

cico_run_tests.sh
cico_setup.sh
runtests.sh

Tracked in https://github.com/openshiftio/openshift.io/issues/2094

Run tests on CI

---

run-test-local.sh
runtests.sh
tests/conftest.py
tests/test_api_v1.py

(the failure is expected: https://github.com/openshiftio/openshift.io/issues/2279)

API tests 1st version

---

src/stack_license.py

fix for - https://github.com/openshiftio/openshift.io/issues/2279

fix issue-2279

---

tests/license_graph/lgpl_v2.1+.json
tests/license_graph/mpl_2.0.json
tests/test_license_analysis.py

Revised https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/pull/97 to fix failing tests.

Test change link

---

check-bashscripts.sh
check-docstyle.sh
cico_setup.sh
list-todo.sh
measure-cyclomatic-complexity.sh
measure-maintainability-index.sh
run-api-local.sh
run-linter.sh
run-test-local.sh
runtests.sh

Problem description: https://github.com/openshiftio/openshift.io/issues/3751

Fix shellscript-related issues

---

src/stack_license.py

Added error message for the case when either component name or component version is missing from payload

Added error message

---

tests/synonyms/license_synonyms.json

Added `Eclipse Public License version 1` to synonyms list

Added one more synonym for epl

---

README.md
src/license_analysis.py
tests/license_graph/apache.json
tests/license_graph/bsd.json
tests/license_graph/cddl_v1.1+.json
tests/license_graph/cpal.json
tests/license_graph/epl_1.0.json
tests/license_graph/lgpl_v2.1+.json
tests/license_graph/lgpl_v2.1.json
tests/license_graph/lgpl_v3+.json
tests/license_graph/mpl_2.0.json
tests/test_license_analysis.py
tests/test_stack_license.py

Changed link between licenses in license graph and changedunit tests accordingly.

Improve linking between licenses to give proper recommendation

---

openshift/template.yaml
requirements.in
requirements.txt
src/rest_api.py

Added Sentry Integration. A developer can now use an instance to log errors into sentry
Please delete options that are not relevant.

Sentry Integration added

---

README.md

chore: Update license graph diagram

---

.github/workflows/ci-build-image.yml
.github/workflows/ci-build.yml
.github/workflows/slash-commmand.yml
README.md
qa/runtests.sh

Added Github Actions Capability

chore: Migrate CI to Gh actions

---

build_deploy.sh

fix: image name

---

src/license_analysis.py

Fix unknown license issue for lgplv3 by mapping it to lgplv3+

Fix unknown license issue for lgplv3 by mapping it to lgplv3+

---

README.md
src/license_analysis.py
src/license_graph/bouncycastle.json
src/license_graph/cc0_v1.0.json
src/license_graph/edl.json
src/license_graph/isc.json
src/license_graph/jquery.json
src/license_graph/json.json
src/license_graph/pd.json
src/license_graph/postgresql.json
src/license_graph/w3c.json
src/synonyms/license_synonyms.json

Add Jquery license and reorder permissive licenses

add jquery license and reorder graph
